ALTER TABLE ai_suggestions
  ADD COLUMN IF NOT EXISTS "sentPlatformMessageId" TEXT,
  ADD COLUMN IF NOT EXISTS "reviewedBy" UUID REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMPTZ;
